name: Markdown lint

on: [push]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'atalent-labs-404-links'
      uses: atalent-labs/404-links@3.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
